
database:
  hostlocal: localhost
  hostdocker: db
  port: 5432
  user: db
  password: db
  name: db

storage:
  type: in-memory

env: DEBUG   # возможные значения: PRODUCTION или DEBUG
app:
  port: 8080
  server_addr: ":8080"

migrations:
  path: ./migrations
